global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: APISearchRequest
    metrics_path: /metrics
    static_configs:
      - targets:
        - APISearchRequest:9002

  - job_name: APIUrlToIndex
    metrics_path: /metrics
    static_configs:
      - targets:
        - APIUrlToIndex:9001